<a href="https://colab.research.google.com/github/annemariet/tutorials/blob/master/Introduction_python_Exo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction

Ce notebook fournit quelques rappels sur [les structures de données DataFrames et Series du module Pandas.](https://pandas.pydata.org/docs/getting_started/dsintro.html)

## Series


Les données peuvent être
- Une valeur scalaire 
- Un dictionnaire Python 
- Un Ndarray

Création d'une série, c'est à dire d'un vecteur de valeurs d'une variable (en général valeurs pour différents individus)

In [0]:
import pandas as pd

 ### valeur scalaire

In [0]:
# Program to Create series with scalar values  
Data =[1, 3, 4, 5, 6, 2, 9]  # Numeric data 
  
# Creating series with default index values 
s = pd.Series(Data) 


In [0]:
# predefined index values 
Index =['a', 'b', 'c', 'd', 'e', 'f', 'g']  
  
# Creating series with predefined index values 
si = pd.Series(Data, Index) 

In [0]:
si

a    1
b    3
c    4
d    5
e    6
f    2
g    9
dtype: int64

In [0]:
si['a']

1

### dictionnaire

Un dictionnaire en python est une sorte de liste mais au lieu d'utiliser des index , on utilise des clés alphanumériques.

In [0]:
# Program to Create Dictionary series 
dictionary ={'a':1, 'b':2, 'c':3, 'd':4, 'e':5}  
  
# Creating series of Dictionary type 
sd = pd.Series(dictionary)  

###  Ndarray

In [0]:
import pandas as pd
# Program to Create ndarray series 
Data =[[2, 3, 4], [5, 6, 7]]  # Defining 2darray 
  
# Creating series of 2darray 
snd = pd.Series(Data) 

In [0]:
Data

[[2, 3, 4], [5, 6, 7]]

In [0]:
snd[0][1]

3

## DataFrames:

C'est une structure de données bidimensionnelle (2-D) qui se compose de lignes et de colonnes.

Les données peuvent être
- Une ou plusieurs  valeur scalaire 
- Un ou plusieurs  dictionnaires 
- 2D-numpy ndarray

In [0]:
# Program to Create Data Frame with two dictionaries 
dict1 ={'a':1, 'b':2, 'c':3, 'd':4}        # Define Dictionary 1 
dict2 ={'a':5, 'b':6, 'c':7, 'd':8, 'e':9} # Define Dictionary 2 
Data = {'first':dict1, 'second':dict2}  # Define Data with dict1 and dict2 
df = pd.DataFrame(Data)  # Create DataFrame 

In [0]:
df

first  second
a    1.0       5
b    2.0       6
c    3.0       7
d    4.0       8
e    NaN       9

###  Series:

In [0]:
# Program to create Dataframe of three series  
import pandas as pd 
  
s1 = pd.Series([1, 3, 4, 5, 6, 2, 9])           # Define series 1 
s2 = pd.Series([1.1, 3.5, 4.7, 5.8, 2.9, 9.3]) # Define series 2 
s3 = pd.Series(['a', 'b', 'c', 'd', 'e'])     # Define series 3 
  
  
Data ={'first':s1, 'second':s2, 'third':s3} # Define Data 
dfseries = pd.DataFrame(Data)              # Create DataFrame 

### 2D-numpy ndarray

In [0]:
# Program to create DataFrame from 2D array 
import pandas as pd # Import Library 
d1 =[[2, 3, 4], [5, 6, 7]] # Define 2d array 1 
d2 =[[2, 4, 8], [1, 3, 9]] # Define 2d array 2 
Data ={'first': d1, 'second': d2} # Define Data  
df2d = pd.DataFrame(Data)    # Create DataFrame 

In [0]:
d1

[[2, 3, 4], [5, 6, 7]]

# Exercice 
Pour cet exercice, nous utilisons une base de données automobile. Ce jeu de données automobile présente une caractéristique différente d’une voiture, telle que la carrosserie, l’empattement, le type de moteur, le prix, le kilométrage, la puissance, etc.


- À partir de ce jeu de données, imprimez les cinq premières et dernières lignes

In [0]:
import pandas as pd
#### YourCode

company   body-style  wheel-base  length engine-type  \
index                                                             
0      alfa-romero  convertible        88.6   168.8        dohc   
1      alfa-romero  convertible        88.6   168.8        dohc   
2      alfa-romero    hatchback        94.5   171.2        ohcv   
3             audi        sedan        99.8   176.6         ohc   
4             audi        sedan        99.4   176.6         ohc   

      num-of-cylinders  horsepower  average-mileage    price  
index                                                         
0                 four         111               21  13495.0  
1                 four         111               21  16500.0  
2                  six         154               19  16500.0  
3                 four         102               24  13950.0  
4                 five         115               18  17450.0

In [0]:
d1=df['company']
d1

index
0       alfa-romero
1       alfa-romero
2       alfa-romero
3              audi
4              audi
5              audi
6              audi
9               bmw
10              bmw
11              bmw
13              bmw
14              bmw
15              bmw
16        chevrolet
17        chevrolet
18        chevrolet
19            dodge
20            dodge
27            honda
28            honda
29            honda
30            isuzu
31            isuzu
32            isuzu
33           jaguar
34           jaguar
35           jaguar
36            mazda
37            mazda
38            mazda
          ...      
43            mazda
44    mercedes-benz
45    mercedes-benz
46    mercedes-benz
47    mercedes-benz
49       mitsubishi
50       mitsubishi
51       mitsubishi
52       mitsubishi
53           nissan
54           nissan
55           nissan
56           nissan
57           nissan
61          porsche
62          porsche
63          porsche
66           toyota
67           t

In [0]:
df.columns

Index(['company', 'body-style', 'wheel-base', 'length', 'engine-type',
       'num-of-cylinders', 'horsepower', 'average-mileage', 'price'],
      dtype='object')

- Trouvez le nom de la compagnie de la voiture la plus chère

In [0]:
import pandas as pd
#### YourCode use "Automobile_data.csv"


company
35  mercedes-benz

*   Affichez tous les détails des voitures Toyota




In [0]:
#### YourCode

company    price body-style
35  mercedes-benz  45400.0    hardtop

- Comptez le nombre total de voitures par entreprise

In [0]:
#### YourCode

toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
volkswagen       4
mitsubishi       4
jaguar           3
chevrolet        3
porsche          3
isuzu            3
alfa-romero      3
honda            3
dodge            2
volvo            2
Name: company, dtype: int64

- 
Trouvez les entreprises qui on les voiture les plus chères

In [0]:
#### YourCode

company    price
company                              
alfa-romero      alfa-romero  16500.0
audi                    audi  18920.0
bmw                      bmw  41315.0
chevrolet          chevrolet   6575.0
dodge                  dodge   6377.0
honda                  honda  12945.0
isuzu                  isuzu   6785.0
jaguar                jaguar  36000.0
mazda                  mazda  18344.0
mercedes-benz  mercedes-benz  45400.0
mitsubishi        mitsubishi   8189.0
nissan                nissan  13499.0
porsche              porsche  37028.0
toyota                toyota  15750.0
volkswagen        volkswagen   9995.0
volvo                  volvo  13415.0

- Trouvez le kilométrage moyen de chaque constructeur de voiture

In [0]:
#### YourCode

average-mileage      length
company                                   
alfa-romero          20.333333  169.600000
audi                 20.000000  180.800000
bmw                  19.000000  185.033333
chevrolet            41.000000  151.933333
dodge                31.000000  157.300000
honda                26.333333  167.200000
isuzu                33.333333  160.833333
jaguar               14.333333  196.966667
mazda                28.000000  164.260000
mercedes-benz        18.000000  197.275000
mitsubishi           29.500000  164.850000
nissan               31.400000  170.140000
porsche              17.000000  171.166667
toyota               28.714286  167.571429
volkswagen           31.750000  171.700000
volvo                23.000000  188.800000

In [0]:
#### YourCode

average-mileage      length
company                                   
alfa-romero          20.333333  169.600000
audi                 20.000000  180.800000
bmw                  19.000000  185.033333
chevrolet            41.000000  151.933333
dodge                31.000000  157.300000
honda                26.333333  167.200000
isuzu                33.333333  160.833333
jaguar               14.333333  196.966667
mazda                28.000000  164.260000
mercedes-benz        18.000000  197.275000
mitsubishi           29.500000  164.850000
nissan               31.400000  170.140000
porsche              17.000000  171.166667
toyota               28.714286  167.571429
volkswagen           31.750000  171.700000
volvo                23.000000  188.800000

In [0]:
mileageDf.columns

Index(['average-mileage', 'length'], dtype='object')

- 
Triez toutes les voitures par colonne de prix

In [0]:
#### YourCode

index        company   body-style  wheel-base  length engine-type  \
35     47  mercedes-benz      hardtop       112.0   199.2        ohcv   
11     14            bmw        sedan       103.5   193.8         ohc   
34     46  mercedes-benz        sedan       120.9   208.1        ohcv   
46     62        porsche  convertible        89.5   168.9        ohcf   
12     15            bmw        sedan       110.0   197.0         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
35            eight         184               14  45400.0  
11              six         182               16  41315.0  
34            eight         184               14  40960.0  
46              six         207               17  37028.0  
12              six         182               15  36880.0

- 
Concaténez deux trames de données en utilisant les conditions suivantes

Créez deux trames de données à l'aide des deux dict suivants, fusionnez deux trames de données et ajoutez le deuxième trame de données en tant que nouvelle colonne au premier.

In [0]:
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

In [0]:
#### YourCode

Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160

- Concaténez deux trames de données Auto1 et auto 2


- Ecrivez un programme Pandas pour convertir un dictionnaire en une série de Pandas.

In [0]:
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}

In [0]:
#### YourCode

-Ecrivez un programme Pandas pour changer l'ordre d'index d'une série donnée
Data Series:
- A 1
- B 2
- C 3
- D 4
- E 5

In [0]:
#### YourCode

# NumPy

La bibliothèque NumPy (http://www.numpy.org/) permet d’effectuer des calculs numériques avec Python. 

In [0]:
import numpy as np

In [0]:
## Variables prédéfinies
Variable pi

In [0]:
np.pi

3.141592653589793

## Tableaux - numpy.array()

### Création
Less tableaux (en anglais, array) peuvent être créés avec numpy.array(). On utilise des crochets pour délimiter les listes d’éléments dans les tableaux.

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6]])

### Affichage

In [0]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
type(a)


numpy.ndarray

On voit que l’on a obtenu un objet de type numpy.ndarray
### Accès aux éléments d’un tableau

In [0]:
a[0,1]

2

In [0]:
a[1,2]

### La fonction numpy.arange()

In [0]:
m = np.arange(3, 15, 2)
m
type(m)

Noter la différence entre numpy.arange() et range() :

- numpy.arange() retourne un objet de type numpy.ndarray.
- range() retourne un objet de type range.

In [0]:
n = range(3, 15, 2)
type(n)

3
5
7
9
11
13


numpy.arange() accepte des arguments qui ne sont pas entiers.

In [0]:
np.arange(0, 11*np.pi, np.pi)

array([ 0.        ,  3.14159265,  6.28318531,  9.42477796, 12.56637061,
       15.70796327, 18.84955592, 21.99114858, 25.13274123, 28.27433388,
       31.41592654])

### La fonction numpy.linspace()
numpy.linspace() permet d’obtenir un tableau 1D allant d’une valeur de départ à une valeur de fin avec un nombre donné d’éléments.

In [0]:
np.linspace(3, 9, 10)

## Action d’une fonction mathématique sur un tableau
NumPy dispose d’un grand nombre de fonctions mathématiques qui peuvent être appliquées directement à un tableau. Dans ce cas, la fonction est appliquée à chacun des éléments du tableau.

In [0]:
x = np.linspace(-np.pi/2, np.pi/2, 3)
y = np.sin(x)
y

array([-1.,  0.,  1.])

# Exercice


Créer un tableau d'entiers 4X2 et afficher ses attributs

Note: element doit être un type de unsigned int16. Et afficher les attributs suivants: -

- La forme d'un tableau.
- Dimensions du tableau.
- La longueur de chaque élément du tableau en octets

In [0]:
#### YourCode

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [0]:
#### YourCode

Printing Array
[[0 0]
 [0 0]
 [0 0]
 [0 0]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


- Créez un tableau d'entiers 5X2 compris entre 100 et 200 de sorte que la différence entre chaque élément soit de 10

In [0]:
#### YourCode

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]



Voici le tableau numPy fourni. retourne un tableau d'éléments dans la troisième colonne de toutes les lignes

In [0]:
import numpy
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

In [0]:
#### YourCode

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[33 66 99]


- 
Voici le tableau numpy retourné, tableau de lignes impaires et de colonnes paires

In [0]:
import numpy
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [0]:
#### YourCode

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 Printing array of odd rows and even columns
[[ 3  6  9 12]
 [27 30 33 36]
 [51 54 57 60]]


- Ajoutez les deux tableaux NumPy suivants et modifiez un tableau de résultats en calculant la racine carrée de chaque élément

In [0]:
import numpy
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

In [0]:
#### YourCode

addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements

[[4.47213595 6.244998   5.74456265]
 [5.         5.         5.29150262]]


- 
Diviser le tableau en quatre sous-tableaux de taille égale

Remarque: Créez un tableau d'entiers 8X3 compris entre 10 et 34 de sorte que la différence entre chaque élément soit égale à 1, puis divisez le tableau en quatre sous-tableaux de taille égale.

In [0]:
#### YourCode

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


- Trier le tableau NumPy suivant
  -  par la deuxième rangée 
  -  par la deuxième colonne

In [0]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

In [0]:
#### YourCode

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting Original array by secoond column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


- 
Voici le tableau à deux dimensions. Imprimer max de l'axe 0 et min de l'axe 1

In [0]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

In [0]:
#### YourCode

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing amin Of Axis 1
[34 12 53]
Printing amax Of Axis 0
[82 94 73]


- 
Voici le tableau d'entrée NumPy, supprimez la deuxième colonne et insérez la nouvelle colonne suivante à la place.

In [0]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = numpy.array([[10,10,10]])

In [0]:
#### YourCode

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


- 
Créer un tableau à deux dimensions et le tracer à l'aide de matplotlib